/**
 * Version information from Git commit
 * This file is auto-generated by scripts/get-version.js
 */

export interface VersionInfo {
  commitHash: string;
  commitDate: string;
  commitMessage: string;
  buildDate: string;
}

// Default version info (used if version.json doesn't exist)
const defaultVersion: VersionInfo = {
  commitHash: 'dev',
  commitDate: new Date().toISOString(),
  commitMessage: 'Development build',
  buildDate: new Date().toISOString(),
};

// Try to load version info, with fallback for development
let versionInfo: VersionInfo = defaultVersion;

// Load version info with error handling
// Using try-catch with dynamic import to handle missing file
(async () => {
  try {
    const versionModule = await import('../version.json');
    versionInfo = (versionModule.default || versionModule) as VersionInfo;
  } catch (e) {
    // If version.json doesn't exist (development), use defaults
    versionInfo = defaultVersion;
  }
})();

export const getVersion = (): VersionInfo => {
  return versionInfo;
};

export const getVersionString = (): string => {
  const v = getVersion();
  try {
    const date = new Date(v.commitDate);
    return `${v.commitHash} (${date.toLocaleDateString('es-ES')})`;
  } catch (e) {
    return v.commitHash;
  }
};

