/**
 * Version information from Git commit
 * This file is auto-generated by scripts/get-version.js
 */

export interface VersionInfo {
  commitHash: string;
  commitDate: string;
  commitMessage: string;
  buildDate: string;
}

// Default version info (used if version.json doesn't exist)
const defaultVersion: VersionInfo = {
  commitHash: 'dev',
  commitDate: new Date().toISOString(),
  commitMessage: 'Development build',
  buildDate: new Date().toISOString(),
};

// Export default version for development
export const getVersion = (): VersionInfo => {
  return defaultVersion;
};

export const getVersionString = (): string => {
  const v = getVersion();
  try {
    const date = new Date(v.commitDate);
    return `${v.commitHash} (${date.toLocaleDateString('es-ES')})`;
  } catch (e) {
    return v.commitHash;
  }
};

