// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://allexcdmfjigijunipxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsbGV4Y2RtZmppZ2lqdW5pcHh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzMzExMTYsImV4cCI6MjA3NzkwNzExNn0.C3hjUziPL1MtlZ7U25NVbRP4055mUKkyonaKF8bXIMI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});